DROP SEQUENCE IF EXISTS PRODUCT_ID_GEN;

CREATE SEQUENCE PRODUCT_ID_GEN
  START WITH 1
  INCREMENT BY 1;
  
DROP TABLE IF EXISTS product;

CREATE TABLE product (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CREATED_AT datetime,
  CREATED_BY	VARCHAR(255),
  UPDATED_BY	VARCHAR(255),
  UPDATED_AT	datetime,
  DESCRIPTION	VARCHAR(255),
  NAME VARCHAR(250) NOT NULL,
  PRICE DOUBLE NOT NULL
);

